services:
  mongo:
    image: mongo:latest
    ports:
      - "27027:27017" # machine:docker ports
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: testdb # 1
      MONGO_INITDB_ROOT_USERNAME: user # 2
      MONGO_INITDB_ROOT_PASSWORD: mongopass # 3

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      MONGO_DATABASE: testdb # 1
      MONGO_USER: user # 2
      MONGO_PASSWORD: mongopass # 3
      MONGO_HOST: mongo
      MONGO_PORT: 27017 # docker port
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo_data: