networks:
  dev:

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    networks:
      - dev

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - dev