services:
  mongo:
    image: mongo:latest
    ports:
      - "27027:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: testdb
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: mongopass

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      MONGO_DATABASE: testdb
      MONGO_USER: user
      MONGO_PASSWORD: mongopass
      MONGO_HOST: mongo
      MONGO_PORT: 27017
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo_data: