services:
  mongo:
    image: mongo:latest
    ports:
      - "27027:27017" # machine:docker ports
    volumes:
      - mongo_data:/data/db
    env_file:
      - .env
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE} # 1
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER} # 2
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD} # 3

  backend:
    build:
      context: ./backend
    ports:
      - "${PORT}:8080"
    env_file:
      - .env
    environment:
      - MONGO_DATABASE=${MONGO_DATABASE} # 1
      - MONGO_USERNAME=${MONGO_USER} # 2
      - MONGO_PASSWORD=${MONGO_PASSWORD} # 3
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=27017 # docker port, DO NOT CHANGE
      - NODE_ENV=${ENVIRONMENT} # 4
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_ENV=${ENVIRONMENT} # 4
        - VITE_APP_NAME=${VITE_APP_NAME}
        - VITE_API_URL=${VITE_API_URL}
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo_data: